// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { IErrorAnalysisTreeNode } from "@responsible-ai/core-ui";

export const dummyTreeWineData: IErrorAnalysisTreeNode[] = [
  {
    arg: undefined,
    badFeaturesRowCount: 0,
    condition: "",
    error: 49,
    id: 0,
    isErrorMetric: true,
    method: "",
    metricName: "Error rate",
    metricValue: 0.550561797752809,
    nodeIndex: 0,
    nodeName: "color_intensity",
    parentId: undefined,
    parentNodeName: "",
    pathFromRoot: "",
    size: 89,
    sourceRowKeyHash: "hashkey",
    success: 40
  },
  {
    arg: 3.8700000000000006,
    badFeaturesRowCount: 0,
    condition: "color_intensity <= 3.87",
    error: 2,
    id: 2,
    isErrorMetric: true,
    method: "less and equal",
    metricName: "Error rate",
    metricValue: 0.05714285714285714,
    nodeIndex: 2,
    nodeName: "",
    parentId: 0,
    parentNodeName: "color_intensity",
    pathFromRoot: "",
    size: 35,
    sourceRowKeyHash: "hashkey",
    success: 33
  },
  {
    arg: 3.8700000000000006,
    badFeaturesRowCount: 0,
    condition: "color_intensity > 3.87",
    error: 47,
    id: 1,
    isErrorMetric: true,
    method: "greater",
    metricName: "Error rate",
    metricValue: 0.8703703703703703,
    nodeIndex: 1,
    nodeName: "proline",
    parentId: 0,
    parentNodeName: "color_intensity",
    pathFromRoot: "",
    size: 54,
    sourceRowKeyHash: "hashkey",
    success: 7
  },
  {
    arg: 666.0000000000001,
    badFeaturesRowCount: 0,
    condition: "proline <= 666.00",
    error: 13,
    id: 3,
    isErrorMetric: true,
    method: "less and equal",
    metricName: "Error rate",
    metricValue: 0.65,
    nodeIndex: 3,
    nodeName: "",
    parentId: 1,
    parentNodeName: "proline",
    pathFromRoot: "",
    size: 20,
    sourceRowKeyHash: "hashkey",
    success: 7
  },
  {
    arg: 666.0000000000001,
    badFeaturesRowCount: 0,
    condition: "proline > 666.00",
    error: 34,
    id: 4,
    isErrorMetric: true,
    method: "greater",
    metricName: "Error rate",
    metricValue: 1,
    nodeIndex: 4,
    nodeName: "",
    parentId: 1,
    parentNodeName: "proline",
    pathFromRoot: "",
    size: 34,
    sourceRowKeyHash: "hashkey",
    success: 0
  }
];
