// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export const dummyTreeData = [
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 827,
    id: 0,
    nodeIndex: 0,
    nodeName: "Feature 1",
    parentId: "",
    parentNodeName: "",
    pathFromRoot: "",
    size: 6513,
    sourceRowKeyHash: "hashkey",
    success: 5686
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 145,
    id: 1,
    nodeIndex: 1,
    nodeName: "Feature 2",
    parentId: 0,
    parentNodeName: 0,
    pathFromRoot: "",
    size: 3533,
    sourceRowKeyHash: "hashkey",
    success: 3388
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 109,
    id: 2,
    nodeIndex: 2,
    nodeName: "Feature 3",
    parentId: 1,
    parentNodeName: 1,
    pathFromRoot: "",
    size: 3336,
    sourceRowKeyHash: "hashkey",
    success: 3227
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 70,
    id: 3,
    nodeIndex: 3,
    nodeName: "Feature 4",
    parentId: 2,
    parentNodeName: 2,
    pathFromRoot: "",
    size: 867,
    sourceRowKeyHash: "hashkey",
    success: 797
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 39,
    id: 4,
    nodeIndex: 4,
    nodeName: "Feature 5",
    parentId: 2,
    parentNodeName: 2,
    pathFromRoot: "",
    size: 2469,
    sourceRowKeyHash: "hashkey",
    success: 2430
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 36,
    id: 5,
    nodeIndex: 5,
    nodeName: "Feature 6",
    parentId: 1,
    parentNodeName: 1,
    pathFromRoot: "",
    size: 197,
    sourceRowKeyHash: "hashkey",
    success: 161
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 2,
    id: 6,
    nodeIndex: 6,
    nodeName: "Feature 7",
    parentId: 5,
    parentNodeName: 5,
    pathFromRoot: "",
    size: 58,
    sourceRowKeyHash: "hashkey",
    success: 56
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 34,
    id: 7,
    nodeIndex: 7,
    nodeName: "Feature 8",
    parentId: 5,
    parentNodeName: 5,
    pathFromRoot: "",
    size: 139,
    sourceRowKeyHash: "hashkey",
    success: 105
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 682,
    id: 8,
    nodeIndex: 8,
    nodeName: "Feature 9",
    parentId: 0,
    parentNodeName: 0,
    pathFromRoot: "",
    size: 2980,
    sourceRowKeyHash: "hashkey",
    success: 2298
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 673,
    id: 9,
    nodeIndex: 9,
    nodeName: "Feature 10",
    parentId: 8,
    parentNodeName: 8,
    pathFromRoot: "",
    size: 2596,
    sourceRowKeyHash: "hashkey",
    success: 1923
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 667,
    id: 10,
    nodeIndex: 10,
    nodeName: "Feature 11",
    parentId: 9,
    parentNodeName: 9,
    pathFromRoot: "",
    size: 2420,
    sourceRowKeyHash: "hashkey",
    success: 1753
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 6,
    id: 11,
    nodeIndex: 11,
    nodeName: "Feature 12",
    parentId: 9,
    parentNodeName: 9,
    pathFromRoot: "",
    size: 176,
    sourceRowKeyHash: "hashkey",
    success: 170
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 9,
    id: 12,
    nodeIndex: 12,
    nodeName: "Feature 13",
    parentId: 8,
    parentNodeName: 8,
    pathFromRoot: "",
    size: 384,
    sourceRowKeyHash: "hashkey",
    success: 375
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 8,
    id: 13,
    nodeIndex: 13,
    nodeName: "Feature 14",
    parentId: 12,
    parentNodeName: 12,
    pathFromRoot: "",
    size: 383,
    sourceRowKeyHash: "hashkey",
    success: 375
  },
  {
    badFeaturesRowCount: 0,
    condition: "condition",
    error: 1,
    id: 14,
    nodeIndex: 14,
    nodeName: "Feature 15",
    parentId: 12,
    parentNodeName: 12,
    pathFromRoot: "",
    size: 1,
    sourceRowKeyHash: "hashkey",
    success: 0
  }
];
