// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export const dummyTreeBreastCancerPrecisionData = [
  {
    arg: "",
    badFeaturesRowCount: 0,
    condition: "",
    error: 47,
    id: 0,
    isErrorMetric: false,
    method: "",
    metricName: "Precision score",
    metricValue: 1,
    nodeIndex: 0,
    nodeName: "worst radius",
    parentId: "",
    parentNodeName: "",
    pathFromRoot: "",
    size: 114,
    sourceRowKeyHash: "hashkey",
    success: 67
  },
  {
    arg: 16.790000000000003,
    badFeaturesRowCount: 0,
    condition: "worst radius <= 16.79",
    error: 5,
    id: 1,
    isErrorMetric: false,
    method: "less and equal",
    metricName: "Precision score",
    metricValue: 1,
    nodeIndex: 1,
    nodeName: "concavity error",
    parentId: 0,
    parentNodeName: "worst radius",
    pathFromRoot: "",
    size: 71,
    sourceRowKeyHash: "hashkey",
    success: 66
  },
  {
    arg: 0.03350500000000001,
    badFeaturesRowCount: 0,
    condition: "concavity error <= 0.03",
    error: 0,
    id: 3,
    isErrorMetric: false,
    method: "less and equal",
    metricName: "Precision score",
    metricValue: 1,
    nodeIndex: 3,
    nodeName: "",
    parentId: 1,
    parentNodeName: "concavity error",
    pathFromRoot: "",
    size: 51,
    sourceRowKeyHash: "hashkey",
    success: 51
  },
  {
    arg: 0.03350500000000001,
    badFeaturesRowCount: 0,
    condition: "concavity error > 0.03",
    error: 5,
    id: 5,
    isErrorMetric: false,
    method: "greater",
    metricName: "Precision score",
    metricValue: 1,
    nodeIndex: 5,
    nodeName: "",
    parentId: 1,
    parentNodeName: "concavity error",
    pathFromRoot: "",
    size: 20,
    sourceRowKeyHash: "hashkey",
    success: 15
  },
  {
    arg: 16.790000000000003,
    badFeaturesRowCount: 0,
    condition: "worst radius > 16.79",
    error: 42,
    id: 2,
    isErrorMetric: false,
    method: "greater",
    metricName: "Precision score",
    metricValue: 1,
    nodeIndex: 2,
    nodeName: "mean area",
    parentId: 0,
    parentNodeName: "worst radius",
    pathFromRoot: "",
    size: 43,
    sourceRowKeyHash: "hashkey",
    success: 1
  },
  {
    arg: 924.4500000000002,
    badFeaturesRowCount: 0,
    condition: "mean area <= 924.45",
    error: 19,
    id: 4,
    isErrorMetric: false,
    method: "less and equal",
    metricName: "Precision score",
    metricValue: 1,
    nodeIndex: 4,
    nodeName: "",
    parentId: 2,
    parentNodeName: "mean area",
    pathFromRoot: "",
    size: 20,
    sourceRowKeyHash: "hashkey",
    success: 1
  },
  {
    arg: 924.4500000000002,
    badFeaturesRowCount: 0,
    condition: "mean area > 924.45",
    error: 23,
    id: 6,
    isErrorMetric: false,
    method: "greater",
    metricName: "Precision score",
    metricValue: 0,
    nodeIndex: 6,
    nodeName: "",
    parentId: 2,
    parentNodeName: "mean area",
    pathFromRoot: "",
    size: 23,
    sourceRowKeyHash: "hashkey",
    success: 0
  }
];
