// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export const dummyTreeBreastCancerData = [
  {
    arg: "",
    badFeaturesRowCount: 0,
    condition: "",
    error: 47,
    id: 0,
    isErrorMetric: true,
    method: "",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 0,
    nodeName: "worst radius",
    parentId: "",
    parentNodeName: "",
    pathFromRoot: "",
    size: 114,
    sourceRowKeyHash: "hashkey",
    success: 67
  },
  {
    arg: 16.789999961853027,
    badFeaturesRowCount: 0,
    condition: "worst radius <= 16.79",
    error: 5,
    id: 1,
    isErrorMetric: true,
    method: "less and equal",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 1,
    nodeName: "worst concave points",
    parentId: 0,
    parentNodeName: "worst radius",
    pathFromRoot: "",
    size: 71,
    sourceRowKeyHash: "hashkey",
    success: 66
  },
  {
    arg: 0.16170000284910202,
    badFeaturesRowCount: 0,
    condition: "worst concave points <= 0.16",
    error: 1,
    id: 2,
    isErrorMetric: true,
    method: "less and equal",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 2,
    nodeName: "mean fractal dimension",
    parentId: 1,
    parentNodeName: "worst concave points",
    pathFromRoot: "",
    size: 67,
    sourceRowKeyHash: "hashkey",
    success: 66
  },
  {
    arg: 0.05432499945163727,
    badFeaturesRowCount: 0,
    condition: "mean fractal dimension <= 0.05",
    error: 1,
    id: 3,
    isErrorMetric: true,
    method: "less and equal",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 3,
    nodeName: "worst symmetry",
    parentId: 2,
    parentNodeName: "mean fractal dimension",
    pathFromRoot: "",
    size: 3,
    sourceRowKeyHash: "hashkey",
    success: 2
  },
  {
    arg: 0.05432499945163727,
    badFeaturesRowCount: 0,
    condition: "mean fractal dimension > 0.05",
    error: 0,
    id: 4,
    isErrorMetric: true,
    method: "greater",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 4,
    nodeName: "worst symmetry",
    parentId: 2,
    parentNodeName: "mean fractal dimension",
    pathFromRoot: "",
    size: 64,
    sourceRowKeyHash: "hashkey",
    success: 64
  },
  {
    arg: 0.16170000284910202,
    badFeaturesRowCount: 0,
    condition: "worst concave points > 0.16",
    error: 4,
    id: 5,
    isErrorMetric: true,
    method: "greater",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 5,
    nodeName: "worst symmetry",
    parentId: 1,
    parentNodeName: "worst concave points",
    pathFromRoot: "",
    size: 4,
    sourceRowKeyHash: "hashkey",
    success: 0
  },
  {
    arg: 16.789999961853027,
    badFeaturesRowCount: 0,
    condition: "worst radius > 16.79",
    error: 42,
    id: 6,
    isErrorMetric: true,
    method: "greater",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 6,
    nodeName: "worst smoothness",
    parentId: 0,
    parentNodeName: "worst radius",
    pathFromRoot: "",
    size: 43,
    sourceRowKeyHash: "hashkey",
    success: 1
  },
  {
    arg: 0.09491999819874763,
    badFeaturesRowCount: 0,
    condition: "worst smoothness <= 0.09",
    error: 0,
    id: 7,
    isErrorMetric: true,
    method: "less and equal",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 7,
    nodeName: "worst symmetry",
    parentId: 6,
    parentNodeName: "worst smoothness",
    pathFromRoot: "",
    size: 1,
    sourceRowKeyHash: "hashkey",
    success: 1
  },
  {
    arg: 0.09491999819874763,
    badFeaturesRowCount: 0,
    condition: "worst smoothness > 0.09",
    error: 42,
    id: 8,
    isErrorMetric: true,
    method: "greater",
    metricName: "Error rate",
    metricValue: 0,
    nodeIndex: 8,
    nodeName: "worst symmetry",
    parentId: 6,
    parentNodeName: "worst smoothness",
    pathFromRoot: "",
    size: 42,
    sourceRowKeyHash: "hashkey",
    success: 0
  }
];
