/* tslint:disable:object-literal-sort-keys */
export const dummyTreeData = [
  {
    id: 0,
    parentId: "",
    size: 6513,
    success: 5686,
    error: 827,
    nodeIndex: 0,
    nodeName: "Feature 1",
    parentNodeName: "",
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 1,
    parentId: 0,
    size: 3533,
    success: 3388,
    error: 145,
    nodeIndex: 1,
    nodeName: "Feature 2",
    parentNodeName: 0,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 2,
    parentId: 1,
    size: 3336,
    success: 3227,
    error: 109,
    nodeIndex: 2,
    nodeName: "Feature 3",
    parentNodeName: 1,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 3,
    parentId: 2,
    size: 867,
    success: 797,
    error: 70,
    nodeIndex: 3,
    nodeName: "Feature 4",
    parentNodeName: 2,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 4,
    parentId: 2,
    size: 2469,
    success: 2430,
    error: 39,
    nodeIndex: 4,
    nodeName: "Feature 5",
    parentNodeName: 2,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 5,
    parentId: 1,
    size: 197,
    success: 161,
    error: 36,
    nodeIndex: 5,
    nodeName: "Feature 6",
    parentNodeName: 1,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 6,
    parentId: 5,
    size: 58,
    success: 56,
    error: 2,
    nodeIndex: 6,
    nodeName: "Feature 7",
    parentNodeName: 5,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 7,
    parentId: 5,
    size: 139,
    success: 105,
    error: 34,
    nodeIndex: 7,
    nodeName: "Feature 8",
    parentNodeName: 5,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 8,
    parentId: 0,
    size: 2980,
    success: 2298,
    error: 682,
    nodeIndex: 8,
    nodeName: "Feature 9",
    parentNodeName: 0,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 9,
    parentId: 8,
    size: 2596,
    success: 1923,
    error: 673,
    nodeIndex: 9,
    nodeName: "Feature 10",
    parentNodeName: 8,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 10,
    parentId: 9,
    size: 2420,
    success: 1753,
    error: 667,
    nodeIndex: 10,
    nodeName: "Feature 11",
    parentNodeName: 9,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 11,
    parentId: 9,
    size: 176,
    success: 170,
    error: 6,
    nodeIndex: 11,
    nodeName: "Feature 12",
    parentNodeName: 9,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 12,
    parentId: 8,
    size: 384,
    success: 375,
    error: 9,
    nodeIndex: 12,
    nodeName: "Feature 13",
    parentNodeName: 8,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 13,
    parentId: 12,
    size: 383,
    success: 375,
    error: 8,
    nodeIndex: 13,
    nodeName: "Feature 14",
    parentNodeName: 12,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  },
  {
    id: 14,
    parentId: 12,
    size: 1,
    success: 0,
    error: 1,
    nodeIndex: 14,
    nodeName: "Feature 15",
    parentNodeName: 12,
    pathFromRoot: "",
    condition: "condition",
    sourceRowKeyHash: "hashkey",
    badFeaturesRowCount: 0
  }
];
