// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { IVisionExplanationDashboardData } from "@responsible-ai/core-ui";

import { images } from "./images";

export const visionData: IVisionExplanationDashboardData = {
  classNames: ["tench"],
  images,
  predictedY: [
    "cocktail_shaker",
    "spindle",
    "African_grey",
    "hockey",
    "beagle",
    "space_heater",
    "bib",
    "sloth_bear",
    "half_track",
    "sunglasses",
    "bolo_tie",
    "barbell",
    "conch",
    "mantis",
    "horse_cart",
    "disk_brake",
    "convertible",
    "groom",
    "basenji",
    "picket_fence",
    "Norfolk_terrier",
    "cocktail_shaker",
    "cocktail_shaker",
    "cocktail_shaker",
    "cocktail_shaker",
    "cocktail_shaker",
    "cocktail_shaker",
    "mantis",
    "mantis",
    "mantis",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site",
    "web_site"
  ],
  trueY: [
    "cocktail_shaker",
    "spindle",
    "African_grey",
    "hockey",
    "beagle",
    "space_heater",
    "bib",
    "sloth_bear",
    "half_track",
    "sunglasses",
    "bolo_tie",
    "barbell",
    "conch",
    "mantis",
    "horse_cart",
    "disk_brake",
    "convertible",
    "groom",
    "basenji",
    "picket_fence",
    "Norfolk_terrier",
    "holster",
    "English_setter",
    "bikini",
    "military_uniform",
    "lens_cap",
    "maillot",
    "steel_drum",
    "hay",
    "malinois",
    "European_fire_salamander",
    "jersey",
    "swing",
    "Yorkshire_terrier",
    "entertainment_center",
    "Blenheim_spaniel",
    "Leonberg",
    "dumbbell",
    "Border_terrier",
    "tiger_beetle",
    "park_bench",
    "geyser",
    "eft",
    "gorilla",
    "German_shepherd",
    "water_buffalo",
    "Blenheim_spaniel",
    "airship",
    "junco",
    "barbershop"
  ]
};
