// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export enum Locators {
  DataAnalysisTab = "#visionDataAnalysisPivot",
  ModelOverviewHeader = "#ModelAssessmentDashboard #modelStatisticsHeader",
  ModelOverview = "#ModelOverview",
  ModelOverviewDescription = "#ModelOverview #modelOverviewDescription",
  ModelOverviewMetricSelection = "#ModelOverview #modelOverviewMetricSelection",
  ModelOverviewFeatureSelection = "#ModelOverview #modelOverviewFeatureSelection",
  ModelOverviewFeatureConfigurationActionButton = "#ModelOverview #modelOverviewFeatureConfigurationActionButton",
  ModelOverviewHeatmapVisualDisplayToggle = "#ModelOverview #modelOverviewHeatmapVisualDisplayToggle",
  ModelOverviewCohortViewSelector = "#ModelOverview #modelOverviewCohortViewSelector",
  ModelOverviewCohortViewSelectorButtons = "#ModelOverview #modelOverviewCohortViewSelector button",
  ModelOverviewCohortViewFeatureCohortViewButton = "#ModelOverview #modelOverviewCohortViewSelector button[name='Feature cohorts']",
  ModelOverviewCohortViewDatasetCohortViewButton = "#ModelOverview #modelOverviewCohortViewSelector button[name='Dataset cohorts']",
  ModelOverviewDatasetCohortStatsTable = "#ModelOverview #modelOverviewDatasetCohortStatsTable",
  ModelOverviewDisaggregatedAnalysisTable = "#ModelOverview #modelOverviewDisaggregatedAnalysisTable",
  ModelOverviewTableYAxisGrid = "#ModelOverview .highcharts-grid-axis > span",
  ModelOverviewHeatmapCells = "#ModelOverview .highcharts-heatmap-series > .highcharts-data-label > text > tspan",
  ModelOverviewDisaggregatedAnalysisBaseCohortDisclaimer = "#ModelOverview #modelOverviewDisaggregatedAnalysisBaseCohortDisclaimer",
  ModelOverviewDisaggregatedAnalysisBaseCohortWarning = "#ModelOverview #modelOverviewDisaggregatedAnalysisBaseCohortWarning",
  ModelOverviewChartPivot = "#ModelOverview #modelOverviewChartPivot",
  ModelOverviewChartPivotItems = "#ModelOverview #modelOverviewChartPivot .ms-Pivot-link",
  ModelOverviewProbabilityDistributionChart = "#ModelOverview #modelOverviewProbabilityDistributionChart",
  ModelOverviewProbabilityDistributionChartToggle = "#ModelOverview #modelOverviewProbabilityDistributionChartToggle",
  ModelOverviewProbabilityDistributionLineChartCohortSelectionButton = "#ModelOverview #modelOverviewProbabilityDistributionLineChartCohortSelectionButton",
  ModelOverviewProbabilityDistributionBoxChartCohortSelectionButton = "#ModelOverview #modelOverviewProbabilityDistributionBoxChartCohortSelectionButton",
  ModelOverviewProbabilityDistributionChartLabelSelectionFlyout = "#ModelOverview #modelOverviewProbabilityDistributionChartLabelSelectionFlyout",
  ModelOverviewProbabilityDistributionChartBoxes = "#ModelOverview #modelOverviewProbabilityDistributionChart .highcharts-boxplot-series  > .highcharts-point",
  ModelOverviewRegressionDistributionChart = "#ModelOverview #modelOverviewRegressionDistributionChart",
  ModelOverviewRegressionDistributionChartBoxes = "#ModelOverview #modelOverviewRegressionDistributionChart .highcharts-boxplot-series > .highcharts-point",
  ModelOverviewMetricChartCohortSelectionButton = "#ModelOverview #modelOverviewMetricChartCohortSelectionButton",
  ModelOverviewMetricChart = "#ModelOverview #ModelOverviewMetricChart",
  ModelOverviewMetricChartBars = "#ModelOverview #ModelOverviewMetricChart .highcharts-bar-series > rect",
  ModelOverviewConfusionMatrix = "#ModelOverview #modelOverviewConfusionMatrix",
  ModelOverviewConfusionMatrixHeatmap = "#ModelOverview #ModelOverviewConfusionMatrix",
  MissingParameterPlaceholder = "#ModelOverview #MissingParameterPlaceholder",
  DataAnalysisTab = "#visionDataAnalysisPivot"
}
