# Run localisation

trigger:
  - main

pool:
  vmImage: "windows-latest"

steps:
- task: OneLocBuild@2
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    locProj: 'Localise/LocProject.json'
    outDir: '$(Build.ArtifactStagingDirectory)'
    isCreatePrSelected: true
    prSourceBranchPrefix: 'locfiles'
    packageSourceAuth: patAuth
    patVariable: $(OneLocBuildPat)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'