# Run localisation

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
- task: OneLocBuild@2
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    locProj: 'Localize/LocProject.json'
    outDir: '$(Build.ArtifactStagingDirectory)'
    isCreatePrSelected: true
    prSourceBranchPrefix: 'locfiles'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'