# Run localisation

trigger: none

pr: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main

pool:
  vmImage: "windows-latest"

steps:
  - task: OneLocBuild@2
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      locProj: "Localise/LocProject.json"
      outDir: "$(Build.ArtifactStagingDirectory)"
      isCreatePrSelected: true
      prSourceBranchPrefix: "locfiles"
      isAutoCompletePrSelected: false
      repoType: gitHub
      gitHubPatVariable: $(GitHubPat)
      packageSourceAuth: patAuth
      patVariable: $(OneLocBuildPat)
      lsBuildWarningLevel: 4
      xLocConsoleLoggingLevel: Verbose

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
