$remoteFilePath = '\\simpleloc\drops\Drops\ML_ChartLibrary_2485\20200712.2\BinDrops\Windows\bin'
$targetFilePath = 'C:\v3\responsible-ai-core\interpret-dashboard\src\Localization'
Copy-Item -Path $remoteFilePath'\cs-CZ\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\cs-CZ.json'
Copy-Item -Path $remoteFilePath'\de-DE\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\de-DE.json'
Copy-Item -Path $remoteFilePath'\es-ES\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\es-ES.json'
Copy-Item -Path $remoteFilePath'\fr-FR\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\fr-FR.json'
Copy-Item -Path $remoteFilePath'\hu-HU\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\hu-HU.json'
Copy-Item -Path $remoteFilePath'\it-IT\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\it-IT.json'
Copy-Item -Path $remoteFilePath'\ja-JP\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\ja-JP.json'
Copy-Item -Path $remoteFilePath'\ko-KR\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\ko-KR.json'
Copy-Item -Path $remoteFilePath'\nl-NL\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\nl-NL.json'
Copy-Item -Path $remoteFilePath'\pl-PL\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\pl-PL.json'
Copy-Item -Path $remoteFilePath'\pt-BR\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\pt-BR.json'
Copy-Item -Path $remoteFilePath'\pt-PT\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\pt-PT.json'
Copy-Item -Path $remoteFilePath'\ru-RU\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\ru-RU.json'
Copy-Item -Path $remoteFilePath'\sv-SE\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\sv-SE.json'
Copy-Item -Path $remoteFilePath'\tr-TR\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\tr-TR.json'
Copy-Item -Path $remoteFilePath'\zh-CN\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\zh-CN.json'
Copy-Item -Path $remoteFilePath'\zh-TW\visualization\dashboard\src\Localization\en.json' -Destination $targetFilePath'\zh-TW.json'