// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { IInterpretData } from "../IInterpretData";

import {
  bostonData,
  bostonDataGlobal,
  bostonDataNoDataset,
  bostonDataNoPredict,
  bostonDataNoY
} from "./bostonData";
import {
  irisData,
  irisDataNoLocal,
  irisGlobal,
  irisNoData,
  irisNoFeatures
} from "./irisData";

const interpretDatasets = {
  automlMimicAdult: {
    featureNames: [
      "Column6",
      "Column5",
      "Column1",
      "Column13",
      "Column11",
      "Column10",
      "Column7",
      "Column8",
      "Column2",
      "Column12",
      "Column9",
      "Column3",
      "Column4",
      "Column14"
    ],
    noDataset: true,
    noPredict: true
  },
  bostonData,
  bostonDataGlobal,
  bostonDataNoDataset,
  bostonDataNoPredict,
  bostonDataNoY,
  breastCancerData: {
    datapoint: 114,
    datasetBarLabel: ["0 - 22", "23 - 45", "46 - 67", "68 - 90", "91 - 113"],
    defaultXAxis: "Index",
    defaultYAxis: "mean radius",
    featureNames: [
      "worst area",
      "worst perimeter",
      "mean area",
      "mean perimeter",
      "area error",
      "worst texture",
      "mean texture",
      "worst radius",
      "mean radius",
      "mean fractal dimen...",
      "texture error",
      "worst smoothness",
      "mean smoothness",
      "mean compactness",
      "worst fractal dime...",
      "mean concave point...",
      "compactness error",
      "symmetry error",
      "worst symmetry",
      "concave points err...",
      "mean concavity",
      "smoothness error",
      "worst compactness",
      "fractal dimension ...",
      "perimeter error",
      "worst concave poin...",
      "mean symmetry",
      "worst concavity",
      "concavity error",
      "radius error"
    ],
    isClassification: true
  },
  ebmData: {
    datapoint: 2,
    datasetBarLabel: ["0", "1"],
    defaultXAxis: "Index",
    defaultYAxis: "Age",
    featureNames: ["Age", "Employment"],
    noFeatureImportance: true,
    noY: true
  },
  ibmData: {
    datapoint: 20,
    datasetBarLabel: ["0 - 3", "4 - 7", "8 - 11", "12 - 15", "16 - 19"],
    defaultXAxis: "Index",
    defaultYAxis: "Age",
    featureNames: [
      "OverTime",
      "JobRole",
      "MaritalStatus",
      "YearsAtCompany",
      "JobSatisfaction",
      "TotalWorkingYears",
      "YearsSinceLastProm...",
      "YearsInCurrentRole",
      "YearsWithCurrManag...",
      "NumCompaniesWorked",
      "EducationField",
      "JobInvolvement",
      "RelationshipSatisf...",
      "EnvironmentSatisfa...",
      "Age",
      "DistanceFromHome",
      "MonthlyIncome",
      "WorkLifeBalance",
      "TrainingTimesLastY...",
      "JobLevel",
      "Department",
      "StockOptionLevel",
      "DailyRate",
      "Gender",
      "BusinessTravel",
      "MonthlyRate",
      "PerformanceRating",
      "Education",
      "HourlyRate",
      "PercentSalaryHike"
    ],
    isClassification: true
  },
  ibmDataInconsistent: {
    datapoint: 20,
    datasetBarLabel: ["0 - 3", "4 - 7", "8 - 11", "12 - 15", "16 - 19"],
    defaultXAxis: "Index",
    defaultYAxis: "Age",
    errorMessage:
      "Inconsistent dimensions. Predicted probability[0] has dimensions 2, expected 1",
    featureNames: [
      "OverTime",
      "JobRole",
      "MaritalStatus",
      "YearsAtCompany",
      "JobSatisfaction",
      "TotalWorkingYears",
      "YearsSinceLastProm...",
      "YearsInCurrentRole",
      "YearsWithCurrManag...",
      "NumCompaniesWorked",
      "EducationField",
      "JobInvolvement",
      "RelationshipSatisf...",
      "EnvironmentSatisfa...",
      "Age",
      "DistanceFromHome",
      "MonthlyIncome",
      "WorkLifeBalance",
      "TrainingTimesLastY...",
      "JobLevel",
      "Department",
      "StockOptionLevel",
      "DailyRate",
      "Gender",
      "BusinessTravel",
      "MonthlyRate",
      "PerformanceRating",
      "Education",
      "HourlyRate",
      "PercentSalaryHike"
    ]
  },
  ibmNoClass: {
    datapoint: 20,
    datasetBarLabel: ["0 - 3", "4 - 7", "8 - 11", "12 - 15", "16 - 19"],
    defaultXAxis: "Index",
    defaultYAxis: "Age",
    featureNames: [
      "OverTime",
      "JobRole",
      "MaritalStatus",
      "YearsAtCompany",
      "JobSatisfaction",
      "TotalWorkingYears",
      "YearsSinceLastProm...",
      "YearsInCurrentRole",
      "YearsWithCurrManag...",
      "NumCompaniesWorked",
      "EducationField",
      "JobInvolvement",
      "RelationshipSatisf...",
      "EnvironmentSatisfa...",
      "Age",
      "DistanceFromHome",
      "MonthlyIncome",
      "WorkLifeBalance",
      "TrainingTimesLastY...",
      "JobLevel",
      "Department",
      "StockOptionLevel",
      "DailyRate",
      "Gender",
      "BusinessTravel",
      "MonthlyRate",
      "PerformanceRating",
      "Education",
      "HourlyRate",
      "PercentSalaryHike"
    ],
    isClassification: true
  },
  irisData,
  irisDataNoLocal,
  irisGlobal,
  irisNoData,
  irisNoFeatures
};
const withType: {
  [key in keyof typeof interpretDatasets]: IInterpretData;
} = interpretDatasets;

export { withType as interpretDatasets };
