name: Responsible AI Widgets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r raiwidgets/requirements-dev.txt
          pip install raiwidgets/

      - name: flake8
        run: flake8

      - name: Run tests
        run: |
          pytest raiwidgets/tests/
