# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  folder_to_upload: dist/apps/dashboard
  blob_account: responsibleai
  blob_container: pullrequest
  blob_path: ${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref }}

on:
  pull_request:
    branches: [main]

jobs:
  ci-typescript:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install yarn -g
      - name: CI
        run: yarn ci
      - name: Upload unit test code coverage
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-coverage-${{ matrix.node-version }}
          path: coverage
      - name: Upload e2e test screen shot
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: e2e-screen-shot-${{ matrix.node-version }}
          path: dist/cypress
      - name: Upload yarn error
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: yarn-error.log-${{ matrix.node-version }}
          path: yarn-error.log
      - id: publish_url
        run: |
          echo "::set-output name=url::https://${{env.blob_account}}.blob.core.windows.net/${{env.blob_container}}/${{env.blob_path}}/index.html"
      - name: Upload dashboard ${{steps.publish_url.outputs.url}}
        uses: Azure/cli@v1.0.0
        with:
          azcliversion: 2.16.0
          inlineScript: |
            az storage blob sync -c "${{env.blob_container}}" --account-name "${{env.blob_account}}" -s "${{env.folder_to_upload}}" -d "${{env.blob_path}}" --connection-string="${{secrets.AZURE_STORAGE_CONNECTION_STRING}}"
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{steps.publish_url.outputs.url}}
          check_for_duplicate_msg: true
