# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more info see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  folder_to_upload: dist/apps/dashboard
  blob_account: responsibleai
  blob_container: pullrequest
  blob_path: ${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref }}

on:
  pull_request:
    branches: [main]

jobs:
  ci-typescript:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install yarn -g
      - name: CI
        run: yarn ci
      - name: Upload unit test code coverage
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: unit-test-coverage-${{ matrix.node-version }}
          path: coverage
      - name: Upload e2e test screen shot
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: e2e-screen-shot-${{ matrix.node-version }}
          path: dist/cypress
      - name: Upload yarn error
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: yarn-error.log-${{ matrix.node-version }}
          path: yarn-error.log
